export const LIVEWIRE_SNAPSHOT_OVERRIDE = {
  fingerprint: {
    id: "StHDshmBLZZGAZuUWezn",
    name: "post-manager-component",
    locale: "en",
    path: "backend/posts",
    method: "GET",
    v: "acj",
  },
  serverMemo: {
    children: [],
    errors: [],
    htmlHash: "0bc800b6",
    data: {
      editingId: null,
      showForm: true,
      search: "",
      statusFilter: "",
      categoryFilter: "",
      tagFilter: "",
      createdByFilter: "",
      fromDate: "",
      toDate: "",
      perPage: "10",
      title: "",
      slug: "",
      description: "",
      seo_title: "",
      seo_description: "",
      seo_keywords: "",
      image: "",
      is_active: true,
      selectedCategories: [],
      selectedTags: [],
      allCategories: {
        "1": "Technology",
        "4": "Game",
        "5": "Entertainment",
        "6": "Sport",
        "7": "SportsEntertainment",
        "8": "WrestlingStar",
        "9": "AEW",
        "10": "ProWrestling",
        "11": "WomensWrestling",
        "12": "Athlete",
        "13": "VintageStyle",
        "14": "Fighter",
        "15": "tv",
      },
      allTags: {
        "11": "Inspiration",
        "12": "LifeJourney",
        "13": "PersonalGrowth",
        "14": "Transformation",
        "15": "SuccessStory",
        "16": "Motivation",
        "17": "BeforeAndAfter",
        "18": "Beauty",
        "19": "Wellness",
        "20": "Lifestyle",
        "21": "TVShows",
        "22": "Series",
        "23": "Entertainment",
        "24": "PopCulture",
        "25": "MustWatch",
        "26": "Recommended",
        "27": "FilmReview ",
        "28": "YouthCulture",
        "29": "Diversity",
        "30": "CharacterAnalysis",
        "31": "Storytelling",
        "32": "Drama",
        "33": "Recommendations",
        "34": "DeepDive",
        "35": "CelebrityLife",
        "36": "PublicFigure",
        "37": "PersonalJourney",
        "38": "Hollywood",
        "39": "News",
        "40": "LifeStory",
        "41": "FamilyLegacy",
        "42": "MovieNews",
        "43": "FilmUpdate",
        "44": "Netflix",
        "45": "Mystery",
        "46": "YoungAdult",
        "47": "Sequel",
        "48": "FilmMaking",
        "49": "ComingSoon",
        "50": "PlotTwist",
        "51": "Fantasy",
        "52": "StarWars",
        "53": "AEW",
        "54": "ProWrestling",
        "55": "WomensWrestling",
        "56": "Athlete",
        "57": "SportsEntertainment",
        "58": "WrestlingStar",
        "59": "VintageStyle",
        "60": "Fighter",
        "61": "HollywoodActress",
        "62": "IconicRoles",
        "63": "FilmStars",
        "64": "MovieReviews",
        "65": "ClassicFilms",
        "66": "TalentedActress",
        "67": "GirlNextDoor",
        "68": "TeenDrama",
        "69": "CharacterActress",
        "70": "Tribute",
        "71": "FilmIndustry",
        "72": "UnforgettablePerformances",
        "73": "Actress",
        "74": "DCComics",
        "75": "SuperheroMovie",
        "76": "CastAnnouncements",
        "77": "Cast",
        "78": "VillainTheories",
        "79": "ComicBookMovies",
        "80": "DCStudios",
        "81": "NintendoSwitch",
        "82": "GamingNews",
        "83": "VideoGames",
        "84": "Nintendo",
        "85": "GameRelease",
        "86": "AnticipatedGame",
        "87": "GamingUpdates",
        "88": "SciFiGaming",
        "89": "Game",
        "90": "ReleaseDate",
        "91": "WhatToWatch",
        "92": "PostApocalyptic",
        "93": "NewSeason",
        "94": "StreamingNow",
        "95": "SpaceExploration",
        "96": "AppleTVPlus",
        "97": "SciFiSeries",
        "98": "ActionFilm",
        "99": "HorrorGame",
        "100": "Capcom",
        "101": "GamingCommunity",
        "102": "SurvivalHorror",
        "103": "NextGenGaming",
        "104": "CannesFilmFestival",
        "105": "Cinema",
        "106": "FilmMakers",
        "107": "FashionIcon",
        "108": "RisingStar",
        "109": "YoungStar",
        "110": "IndianCinema",
        "111": "Bollywood",
        "112": "tv",
      },
      allUsers: {
        "2": "User 1",
        "3": "User 2",
      },
      slugType: "default",
      selectedPosts: [],
      selectAll: false,
      developDebug: false,
      cloneCount: 1,
      canUseShortlink: false,
      shortlinkPostId: null,
      shortlinkSelectedDomain: "",
      shortlinkDomains: [],
      shortlinkExistingLinks: [],
      shortlinkDomainSearch: "",
      shortlinkCreateMode: false,
      showShortlinkModal: false,
      shortlinkReady: false,
      page: 1,
      paginators: {
        page: 1,
      },
    },
    dataMeta: [],
    checksum: "bdcf8f512839e358f22d58f5bb45f0ea485168416a678cf50a9823f75e03ad35",
  },
  updates: [
    {
      type: "syncInput",
      payload: {
        id: "det3",
        name: "title",
        value: "111",
      },
    },
    {
      type: "callMethod",
      payload: {
        id: "oro3l",
        method: "$set",
        params: ["description", ""],
      },
    },
  ],
};
